main: com.zp4rker.diskit.Diskit

name: Diskit
version: ${version}
author: zp4rker
description: A simple Discord -> Bukkit bridge.
api-version: 1.16
depend: [Bukkot]

commands:
  link:
    description: The command used to link your Minecraft account to your Discord account.
    usage: /link <username#0000 | userId>